import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
	en: {
		lobby: {
			browseChannels: "Browse Channels",
			public: "Public",
			private: "Private",
			myChannels: "My Channels",
			searchPlaceholder: "Search channels...",
			connecting: "Connecting to server...",
			createChannel: "Create Channel",
			acceptCookies: "Accept Cookies",
			loginToCreate: "Log in to Create",
			noChannelsFound: "No channels found matching",
			live: "Live",
			createNewChannel: "Create New Channel",
			channelName: "Channel Name",
			channelNamePlaceholder: "e.g. Late Night Vibes",
			privacy: "Privacy",
			passwordOptional: "Password (Optional)",
			passwordPlaceholder: "Leave empty for unlisted channel",
			cancel: "Cancel",
			enterPassword: "Enter Password",
			passwordInputPlaceholder: "Channel password...",
			unlockJoin: "Unlock & Join",
			welcome: "Welcome",
			signOut: "Sign Out",
			signInGoogle: "Sign in with Google",
			deleteAccount: "Delete Account",
			deleteAccountConfirm: "Are you absolutely sure?",
			deleteAccountWarning: "This action cannot be undone. It will permanently delete your account and <strong>all channels</strong> you have created.",
			deleteAccountType: "Type",
			deleteAccountPhrase: "Delete this account and all my channels forever",
			deleteAccountToConfirm: "to confirm",
			delete: "Delete",
			terms: "Terms & Legal"
		},
		header: {
			profileSettings: "Profile & Settings",
			signIn: "Sign in with Google",
			acceptCookies: "Accept cookies to sign in",
			legal: "Legal Information",
			playlist: "Playlist",
			library: "Library",
			share: "Share Channel",
			suggest: "Suggest",
			suggestionsDisabled: "Suggestions disabled by owner (View Only)",
			suggestSong: "Suggest a Song",
			settings: "Channel Settings",
			reviewRequests: "Review Requests",
			allowSuggestions: "Allow Suggestions",
			manualReview: "Manual Review",
			approveKnown: "Approve known",
			approveKnownTooltip: "Automatically approve songs that have been approved before",
			musicOnly: "Music Only",
			maxLength: "Max Length",
			noLimit: "No Limit",
			mins: "Mins",
			maxQueueSize: "Max Queue Size",
			songs: "Songs",
			preventRepetition: "Prevent Repetition",
			smartQueue: "Smart Queue",
			smartQueueTooltip: "Replace downvoted songs when full",
			autoRefill: "Auto Refill",
			autoRefillTooltip: "Automatically add songs from history when queue is empty. Starts at 5 songs.",
			venueMode: "Venue Mode",
			venueModeTooltip: "Guests see playlist only (No Video)",
			allowPrelisten: "Allow Prelisten",
			allowVoting: "Allow Voting",
			ownerBypassRules: "Owner Bypass Rules",
			ownerBypassRulesTooltip: "Ignore filters/limits",
			ownerBypassQueue: "Owner Bypass Queue",
			ownerBypassQueueTooltip: "Owner songs play next (Top Priority)",
			popups: "Popups",
			deleteChannel: "Delete Channel",
			deleteChannelWarning: "This action is permanent and cannot be undone.",
			deleteChannelTitle: "Delete Channel?",
			deleteChannelConfirmPhrase: "Delete this channel forever",
			deleteChannelType: "Type confirmation phrase...",
			leaveChannel: "Leave Channel?",
			leaveChannelConfirm: "Are you sure you want to return to the lobby?",
			leave: "Leave",
			copyUrl: "Copy URL",
			close: "Close"
		},
		suggest: {
			placeholder: "Type a song name...",
			disabledPlaceholder: "Suggestions disabled by owner",
			submit: "Submit",
			adding: "Adding...",
			added: "Added",
			error: "Please enter a YouTube link or song name."
		},
		app: {
			switching: "Switching Channels...",
			channelNotFound: "Channel does not exist",
			notFoundMessage: "The channel you are looking for ({roomId}) could not be found.",
			goToLobby: "Go to Lobby",
			privateChannel: "Private Channel",
			lockedMessage: "This channel is password protected. Please enter the password to join.",
			unlock: "Unlock"
		},
		track: {
			playing: "Playing",
			now: "Now",
			add: "Add to Queue",
			preview: "Preview Song",
			cancel: "Cancel",
			confirmDelete: "Confirm Delete",
			delete: "Delete Song",
			watch: "Watch on YouTube"
		},
		library: {
			searchPlaceholder: "Search library...",
			songsCount: "{count} song",
			songsCountPlural: "{count} songs",
			inLibrary: "in library",
			info1: "This library displays unique songs played in the last <strong>28 days</strong>.",
			info2: "Older songs are hidden to ensure metadata freshness, but they are <strong>never deleted</strong>. The <strong>Auto Refill</strong> feature still remembers your entire history and will automatically bring older songs back into the queue (and this list) when needed!",
			empty: "No songs found"
		},
		pending: {
			title: "Pending Requests",
			pendingReview: "Pending Review",
			bannedSongs: "Banned Songs",
			empty: "No pending requests",
			emptySubtitle: "New suggestions requiring approval will appear here.",
			suggestedBy: "Suggested by",
			unknown: "Unknown",
			by: "By",
			preview: "Preview",
			ban: "Ban",
			decline: "Decline",
			accept: "Accept"
		},
		playlist: {
			close: "Close Playlist",
			history: "History",
			last50: "Last 50 of {count}",
			nowPlaying: "Now Playing",
			upNext: "Up Next",
			queueEmpty: "Queue empty",
			backToNow: "Back to Now"
		}
	},
	nl: {
		lobby: {
			browseChannels: "Kanalen Bladeren",
			public: "Openbaar",
			private: "Privé",
			myChannels: "Mijn Kanalen",
			searchPlaceholder: "Zoek kanalen...",
			connecting: "Verbinden met server...",
			createChannel: "Kanaal Maken",
			acceptCookies: "Cookies Accepteren",
			loginToCreate: "Log in om te Maken",
			noChannelsFound: "Geen kanalen gevonden voor",
			live: "Live",
			createNewChannel: "Nieuw Kanaal Maken",
			channelName: "Kanaalnaam",
			channelNamePlaceholder: "bijv. Laatavond Sfeer",
			privacy: "Privacy",
			passwordOptional: "Wachtwoord (Optioneel)",
			passwordPlaceholder: "Laat leeg voor verborgen kanaal",
			cancel: "Annuleren",
			enterPassword: "Voer Wachtwoord In",
			passwordInputPlaceholder: "Kanaalwachtwoord...",
			unlockJoin: "Ontgrendel & Doe Mee",
			welcome: "Welkom",
			signOut: "Uitloggen",
			signInGoogle: "Inloggen met Google",
			deleteAccount: "Account Verwijderen",
			deleteAccountConfirm: "Weet je het zeker?",
			deleteAccountWarning: "Deze actie kan niet ongedaan worden gemaakt. Het verwijdert permanent je account en <strong>alle kanalen</strong> die je hebt gemaakt.",
			deleteAccountType: "Typ",
			deleteAccountPhrase: "Verwijder dit account en al mijn kanalen voor altijd",
			deleteAccountToConfirm: "om te bevestigen",
			delete: "Verwijderen",
			terms: "Voorwaarden & Juridisch"
		},
		header: {
			profileSettings: "Profiel & Instellingen",
			signIn: "Inloggen met Google",
			acceptCookies: "Accepteer cookies om in te loggen",
			legal: "Juridische Informatie",
			playlist: "Afspeellijst",
			library: "Bibliotheek",
			share: "Deel Kanaal",
			suggest: "Voorstellen",
			suggestionsDisabled: "Suggesties uitgeschakeld door eigenaar (Alleen Kijken)",
			suggestSong: "Stel een nummer voor",
			settings: "Kanaal Instellingen",
			reviewRequests: "Verzoeken Beoordelen",
			allowSuggestions: "Suggesties Toestaan",
			manualReview: "Handmatige Beoordeling",
			approveKnown: "Bekende goedkeuren",
			approveKnownTooltip: "Keur automatisch nummers goed die eerder zijn goedgekeurd",
			musicOnly: "Alleen Muziek",
			maxLength: "Max Lengte",
			noLimit: "Geen Limiet",
			mins: "Min",
			maxQueueSize: "Max Wachtrij Grootte",
			songs: "Nummers",
			preventRepetition: "Herhaling Voorkomen",
			smartQueue: "Slimme Wachtrij",
			smartQueueTooltip: "Vervang laaggewaardeerde nummers wanneer vol",
			autoRefill: "Automatisch Aanvullen",
			autoRefillTooltip: "Voeg automatisch nummers toe uit geschiedenis bij lege wachtrij. Start bij 5 nummers.",
			venueMode: "Locatie Modus",
			venueModeTooltip: "Gasten zien alleen afspeellijst (Geen Video)",
			allowPrelisten: "Voorluisteren Toestaan",
			allowVoting: "Stemmen Toestaan",
			ownerBypassRules: "Eigenaar Negeert Regels",
			ownerBypassRulesTooltip: "Negeer filters/limieten",
			ownerBypassQueue: "Eigenaar Negeert Wachtrij",
			ownerBypassQueueTooltip: "Eigenaarnummers spelen volgende (Hoogste Prioriteit)",
			popups: "Popups",
			deleteChannel: "Kanaal Verwijderen",
			deleteChannelWarning: "Deze actie is permanent en kan niet ongedaan worden gemaakt.",
			deleteChannelTitle: "Kanaal Verwijderen?",
			deleteChannelConfirmPhrase: "Verwijder dit kanaal voor altijd",
			deleteChannelType: "Typ bevestigingszin...",
			leaveChannel: "Kanaal Verlaten?",
			leaveChannelConfirm: "Weet je zeker dat je terug naar de lobby wilt?",
			leave: "Verlaten",
			copyUrl: "URL Kopiëren",
			close: "Sluiten"
		},
		suggest: {
			placeholder: "Typ een titel...",
			disabledPlaceholder: "Suggesties uitgeschakeld",
			submit: "Dien in",
			adding: "Toevoegen...",
			added: "Toegevoegd",
			error: "Voer een YouTube-link of titel in."
		},
		app: {
			switching: "Kanaal Wisselen...",
			channelNotFound: "Kanaal bestaat niet",
			notFoundMessage: "Het kanaal dat je zoekt ({roomId}) kon niet worden gevonden.",
			goToLobby: "Ga naar Lobby",
			privateChannel: "Privé Kanaal",
			lockedMessage: "Dit kanaal is beveiligd. Voer het wachtwoord in om deel te nemen.",
			unlock: "Ontgrendel"
		},
		track: {
			playing: "Speelt nu",
			now: "Nu",
			add: "In Wachtrij",
			preview: "Voorbeeld",
			cancel: "Annuleren",
			confirmDelete: "Bevestig",
			delete: "Verwijder",
			watch: "Op YouTube"
		},
		library: {
			searchPlaceholder: "Zoek in bibliotheek...",
			songsCount: "{count} nummer",
			songsCountPlural: "{count} nummers",
			inLibrary: "in bibliotheek",
			info1: "Deze bibliotheek toont unieke nummers gespeeld in de laatste <strong>28 dagen</strong>.",
			info2: "Oudere nummers worden verborgen voor metadata-versheid, maar worden <strong>nooit verwijderd</strong>. De <strong>Automatisch Aanvullen</strong> functie onthoudt je volledige geschiedenis en zet oudere nummers automatisch terug in de wachtrij (en deze lijst) wanneer nodig!",
			empty: "Geen nummers gevonden"
		},
		pending: {
			title: "In afwachting",
			pendingReview: "Beoordelen",
			bannedSongs: "Verboden Nummers",
			empty: "Geen verzoeken",
			emptySubtitle: "Nieuwe suggesties verschijnen hier.",
			suggestedBy: "Voorgesteld door",
			unknown: "Onbekend",
			by: "Door",
			preview: "Voorbeeld",
			ban: "Verban",
			decline: "Afwijzen",
			accept: "Accepteren"
		},
		playlist: {
			close: "Sluit Afspeellijst",
			history: "Geschiedenis",
			last50: "Laatste 50 van {count}",
			nowPlaying: "Nu Spelend",
			upNext: "Volgende",
			queueEmpty: "Wachtrij leeg",
			backToNow: "Terug naar Nu"
		}
	},
	de: { // German
		lobby: {
			browseChannels: "Kanäle Durchsuchen",
			public: "Öffentlich",
			private: "Privat",
			myChannels: "Meine Kanäle",
			searchPlaceholder: "Kanäle suchen...",
			connecting: "Verbinde mit Server...",
			createChannel: "Kanal Erstellen",
			acceptCookies: "Cookies Akzeptieren",
			loginToCreate: "Anmelden zum Erstellen",
			noChannelsFound: "Keine Kanäle gefunden für",
			live: "Live",
			createNewChannel: "Neuen Kanal Erstellen",
			channelName: "Kanalname",
			channelNamePlaceholder: "z.B. Late Night Vibes",
			privacy: "Privatsphäre",
			passwordOptional: "Passwort (Optional)",
			passwordPlaceholder: "Leer lassen für ungelisteten Kanal",
			cancel: "Abbrechen",
			enterPassword: "Passwort Eingeben",
			passwordInputPlaceholder: "Kanalpasswort...",
			unlockJoin: "Entsperren & Beitreten",
			welcome: "Willkommen",
			signOut: "Abmelden",
			signInGoogle: "Mit Google Anmelden",
			deleteAccount: "Konto Löschen",
			deleteAccountConfirm: "Bist du sicher?",
			deleteAccountWarning: "Dies kann nicht rückgängig gemacht werden. Dein Konto und <strong>alle Kanäle</strong>, die du erstellt hast, werden dauerhaft gelöscht.",
			deleteAccountType: "Tippe",
			deleteAccountPhrase: "Lösche dieses Konto und alle meine Kanäle für immer",
			deleteAccountToConfirm: "zum Bestätigen",
			delete: "Löschen",
			terms: "Rechtliches"
		},
		header: {
			profileSettings: "Profil & Einstellungen",
			signIn: "Mit Google Anmelden",
			acceptCookies: "Cookies akzeptieren zum Anmelden",
			legal: "Rechtliche Informationen",
			playlist: "Wiedergabeliste",
			library: "Bibliothek",
			share: "Kanal Teilen",
			suggest: "Vorschlagen",
			suggestionsDisabled: "Vorschläge deaktiviert (Nur Ansicht)",
			suggestSong: "Song Vorschlagen",
			settings: "Kanal Einstellungen",
			reviewRequests: "Anfragen Überprüfen",
			allowSuggestions: "Vorschläge Erlauben",
			manualReview: "Manuelle Überprüfung",
			approveKnown: "Bekannte genehmigen",
			approveKnownTooltip: "Automatisch Songs genehmigen, die zuvor genehmigt wurden",
			musicOnly: "Nur Musik",
			maxLength: "Max Länge",
			noLimit: "Kein Limit",
			mins: "Min",
			maxQueueSize: "Max Warteschlange",
			songs: "Songs",
			preventRepetition: "Wiederholung Verhindern",
			smartQueue: "Smarte Warteschlange",
			smartQueueTooltip: "Ersetze schlecht bewertete Songs wenn voll",
			autoRefill: "Auto-Auffüllen",
			autoRefillTooltip: "Füge automatisch Songs aus Verlauf hinzu wenn leer. Startet bei 5 Songs.",
			venueMode: "Veranstaltungsmodus",
			venueModeTooltip: "Gäste sehen nur Playlist (Kein Video)",
			allowPrelisten: "Vorhören Erlauben",
			allowVoting: "Abstimmen Erlauben",
			ownerBypassRules: "Besitzer ignoriert Regeln",
			ownerBypassRulesTooltip: "Filter/Limits ignorieren",
			ownerBypassQueue: "Besitzer ignoriert Warteschlange",
			ownerBypassQueueTooltip: "Besitzer-Songs spielen als nächstes (Top Priorität)",
			popups: "Popups",
			deleteChannel: "Kanal Löschen",
			deleteChannelWarning: "Diese Aktion ist dauerhaft.",
			deleteChannelTitle: "Kanal Löschen?",
			deleteChannelConfirmPhrase: "Lösche diesen Kanal für immer",
			deleteChannelType: "Bestätigungsphrase eingeben...",
			leaveChannel: "Kanal Verlassen?",
			leaveChannelConfirm: "Möchtest du wirklich zur Lobby zurückkehren?",
			leave: "Verlassen",
			copyUrl: "URL Kopieren",
			close: "Schließen"
		},
		suggest: {
			placeholder: "Songtitel eingeben...",
			disabledPlaceholder: "Vorschläge deaktiviert",
			submit: "Senden",
			adding: "Hinzufügen...",
			added: "Hinzugefügt",
			error: "Bitte YouTube-Link oder Titel eingeben."
		},
		app: {
			switching: "Kanal wechseln...",
			channelNotFound: "Kanal existiert nicht",
			notFoundMessage: "Der gesuchte Kanal ({roomId}) wurde nicht gefunden.",
			goToLobby: "Zur Lobby",
			privateChannel: "Privater Kanal",
			lockedMessage: "Dieser Kanal ist passwortgeschützt.",
			unlock: "Entsperren"
		},
		track: {
			playing: "Wiedergabe",
			now: "Jetzt",
			add: "In Warteschlange",
			preview: "Vorschau",
			cancel: "Abbrechen",
			confirmDelete: "Bestätigen",
			delete: "Löschen",
			watch: "Auf YouTube"
		}
	},
	fr: { // French
		lobby: {
			browseChannels: "Parcourir les chaînes",
			public: "Public",
			private: "Privé",
			myChannels: "Mes Chaînes",
			searchPlaceholder: "Rechercher des chaînes...",
			connecting: "Connexion au serveur...",
			createChannel: "Créer une Chaîne",
			acceptCookies: "Accepter les Cookies",
			loginToCreate: "Se connecter pour créer",
			noChannelsFound: "Aucune chaîne trouvée pour",
			live: "En direct",
			createNewChannel: "Créer une Nouvelle Chaîne",
			channelName: "Nom de la Chaîne",
			channelNamePlaceholder: "ex. Ambiance Nocturne",
			privacy: "Confidentialité",
			passwordOptional: "Mot de passe (Optionnel)",
			passwordPlaceholder: "Laisser vide pour chaîne non répertoriée",
			cancel: "Annuler",
			enterPassword: "Entrer le Mot de Passe",
			passwordInputPlaceholder: "Mot de passe de la chaîne...",
			unlockJoin: "Déverrouiller & Rejoindre",
			welcome: "Bienvenue",
			signOut: "Se Déconnecter",
			signInGoogle: "Se connecter avec Google",
			deleteAccount: "Supprimer le Compte",
			deleteAccountConfirm: "Êtes-vous sûr ?",
			deleteAccountWarning: "Cette action est irréversible. Elle supprimera définitivement votre compte et <strong>toutes les chaînes</strong> que vous avez créées.",
			deleteAccountType: "Tapez",
			deleteAccountPhrase: "Supprimer ce compte et toutes mes chaînes pour toujours",
			deleteAccountToConfirm: "pour confirmer",
			delete: "Supprimer",
			terms: "Conditions & Légal"
		},
		header: {
			profileSettings: "Profil & Paramètres",
			signIn: "Se connecter avec Google",
			acceptCookies: "Accepter les cookies pour se connecter",
			legal: "Informations Légales",
			playlist: "Playlist",
			library: "Bibliothèque",
			share: "Partager",
			suggest: "Suggérer",
			suggestionsDisabled: "Suggestions désactivées (Lecture seule)",
			suggestSong: "Suggérer une chanson",
			settings: "Paramètres de la Chaîne",
			reviewRequests: "Examiner les demandes",
			allowSuggestions: "Autoriser les suggestions",
			manualReview: "Examen manuel",
			approveKnown: "Approuver connus",
			approveKnownTooltip: "Approuver automatiquement les chansons déjà approuvées",
			musicOnly: "Musique Seulement",
			maxLength: "Durée Max",
			noLimit: "Pas de limite",
			mins: "Min",
			maxQueueSize: "Taille Max File",
			songs: "Chansons",
			preventRepetition: "Éviter Répétition",
			smartQueue: "File Intelligente",
			smartQueueTooltip: "Remplacer les chansons mal notées si plein",
			autoRefill: "Remplissage Auto",
			autoRefillTooltip: "Ajouter auto de l'historique si vide. Démarre à 5 chansons.",
			venueMode: "Mode Lieu",
			venueModeTooltip: "Les invités voient playlist seulement (Pas de Vidéo)",
			allowPrelisten: "Pré-écoute",
			allowVoting: "Votes",
			ownerBypassRules: "Propriétaire ignore règles",
			ownerBypassRulesTooltip: "Ignorer filtres/limites",
			ownerBypassQueue: "Propriétaire ignore file",
			ownerBypassQueueTooltip: "Chansons du propriétaire jouées ensuite (Priorité Top)",
			popups: "Popups",
			deleteChannel: "Supprimer la Chaîne",
			deleteChannelWarning: "Cette action est permanente.",
			deleteChannelTitle: "Supprimer la Chaîne ?",
			deleteChannelConfirmPhrase: "Supprimer cette chaîne pour toujours",
			deleteChannelType: "Tapez la phrase de confirmation...",
			leaveChannel: "Quitter la Chaîne ?",
			leaveChannelConfirm: "Voulez-vous vraiment retourner au lobby ?",
			leave: "Quitter",
			copyUrl: "Copier URL",
			close: "Fermer"
		},
		suggest: {
			placeholder: "Tapez un titre...",
			disabledPlaceholder: "Suggestions désactivées",
			submit: "Envoyer",
			adding: "Ajout...",
			added: "Ajouté",
			error: "Entrez un lien YouTube ou un titre."
		},
		app: {
			switching: "Changement de Chaîne...",
			channelNotFound: "Chaîne inexistante",
			notFoundMessage: "La chaîne recherchée ({roomId}) est introuvable.",
			goToLobby: "Aller au Lobby",
			privateChannel: "Chaîne Privée",
			lockedMessage: "Cette chaîne est protégée par mot de passe.",
			unlock: "Déverrouiller"
		},
		track: {
			playing: "Lecture",
			now: "Maintenant",
			add: "Ajouter",
			preview: "Aperçu",
			cancel: "Annuler",
			confirmDelete: "Confirmer",
			delete: "Supprimer",
			watch: "Sur YouTube"
		}
	},
	es: { // Spanish
		lobby: {
			browseChannels: "Explorar Canales",
			public: "Público",
			private: "Privado",
			myChannels: "Mis Canales",
			searchPlaceholder: "Buscar canales...",
			connecting: "Conectando al servidor...",
			createChannel: "Crear Canal",
			acceptCookies: "Aceptar Cookies",
			loginToCreate: "Inicia sesión para crear",
			noChannelsFound: "No se encontraron canales para",
			live: "En vivo",
			createNewChannel: "Crear Nuevo Canal",
			channelName: "Nombre del Canal",
			channelNamePlaceholder: "ej. Vibras Nocturnas",
			privacy: "Privacidad",
			passwordOptional: "Contraseña (Opcional)",
			passwordPlaceholder: "Dejar vacío para canal no listado",
			cancel: "Cancelar",
			enterPassword: "Introducir Contraseña",
			passwordInputPlaceholder: "Contraseña del canal...",
			unlockJoin: "Desbloquear y Unirse",
			welcome: "Bienvenido",
			signOut: "Cerrar Sesión",
			signInGoogle: "Iniciar sesión con Google",
			deleteAccount: "Eliminar Cuenta",
			deleteAccountConfirm: "¿Estás seguro?",
			deleteAccountWarning: "Esta acción no se puede deshacer. Eliminará permanentemente tu cuenta y <strong>todos los canales</strong> que hayas creado.",
			deleteAccountType: "Escribe",
			deleteAccountPhrase: "Eliminar esta cuenta y todos mis canales para siempre",
			deleteAccountToConfirm: "para confirmar",
			delete: "Eliminar",
			terms: "Términos y Legal"
		},
		header: {
			profileSettings: "Perfil y Configuración",
			signIn: "Iniciar sesión con Google",
			acceptCookies: "Aceptar cookies para entrar",
			legal: "Información Legal",
			playlist: "Lista",
			library: "Biblioteca",
			share: "Compartir",
			suggest: "Sugerir",
			suggestionsDisabled: "Sugerencias desactivadas (Solo ver)",
			suggestSong: "Sugerir canción",
			settings: "Configuración del Canal",
			reviewRequests: "Revisar Peticiones",
			allowSuggestions: "Permitir Sugerencias",
			manualReview: "Revisión Manual",
			approveKnown: "Aprobar conocidos",
			approveKnownTooltip: "Aprobar auto canciones ya aprobadas antes",
			musicOnly: "Solo Música",
			maxLength: "Longitud Máx",
			noLimit: "Sin Límite",
			mins: "Min",
			maxQueueSize: "Tamaño Máx Cola",
			songs: "Canciones",
			preventRepetition: "Evitar Repetición",
			smartQueue: "Cola Inteligente",
			smartQueueTooltip: "Reemplazar canciones mal votadas si está llena",
			autoRefill: "Relleno Auto",
			autoRefillTooltip: "Añadir auto de historial si vacía. Empieza con 5 canciones.",
			venueMode: "Modo Local",
			venueModeTooltip: "Invitados solo ven lista (Sin Video)",
			allowPrelisten: "Permitir Pre-escucha",
			allowVoting: "Permitir Votos",
			ownerBypassRules: "Dueño ignora reglas",
			ownerBypassRulesTooltip: "Ignorar filtros/límites",
			ownerBypassQueue: "Dueño ignora cola",
			ownerBypassQueueTooltip: "Canciones del dueño van después (Prioridad Top)",
			popups: "Popups",
			deleteChannel: "Eliminar Canal",
			deleteChannelWarning: "Esta acción es permanente.",
			deleteChannelTitle: "¿Eliminar Canal?",
			deleteChannelConfirmPhrase: "Eliminar este canal para siempre",
			deleteChannelType: "Escribe la frase de confirmación...",
			leaveChannel: "¿Salir del Canal?",
			leaveChannelConfirm: "¿Seguro que quieres volver al lobby?",
			leave: "Salir",
			copyUrl: "Copiar URL",
			close: "Cerrar"
		},
		suggest: {
			placeholder: "Escribe un título...",
			disabledPlaceholder: "Sugerencias desactivadas",
			submit: "Enviar",
			adding: "Añadiendo...",
			added: "Añadido",
			error: "Introduce un enlace de YouTube o título."
		},
		app: {
			switching: "Cambiando Canales...",
			channelNotFound: "El canal no existe",
			notFoundMessage: "No se encontró el canal ({roomId}).",
			goToLobby: "Ir al Lobby",
			privateChannel: "Canal Privado",
			lockedMessage: "Este canal está protegido con contraseña.",
			unlock: "Desbloquear"
		},
		track: {
			playing: "Reproduciendo",
			now: "Ahora",
			add: "Añadir",
			preview: "Vista previa",
			cancel: "Cancelar",
			confirmDelete: "Confirmar",
			delete: "Eliminar",
			watch: "En YouTube"
		}
	},
	it: { // Italian
		lobby: {
			browseChannels: "Sfoglia Canali",
			public: "Pubblico",
			private: "Privato",
			myChannels: "I Miei Canali",
			searchPlaceholder: "Cerca canali...",
			connecting: "Connessione al server...",
			createChannel: "Crea Canale",
			acceptCookies: "Accetta Cookie",
			loginToCreate: "Accedi per Creare",
			noChannelsFound: "Nessun canale trovato per",
			live: "Live",
			createNewChannel: "Crea Nuovo Canale",
			channelName: "Nome Canale",
			channelNamePlaceholder: "es. Late Night Vibes",
			privacy: "Privacy",
			passwordOptional: "Password (Opzionale)",
			passwordPlaceholder: "Lascia vuoto per canale non in elenco",
			cancel: "Annulla",
			enterPassword: "Inserisci Password",
			passwordInputPlaceholder: "Password canale...",
			unlockJoin: "Sblocca & Entra",
			welcome: "Benvenuto",
			signOut: "Esci",
			signInGoogle: "Accedi con Google",
			deleteAccount: "Elimina Account",
			deleteAccountConfirm: "Sei sicuro?",
			deleteAccountWarning: "Questa azione non può essere annullata. Eliminerà permanentemente il tuo account e <strong>tutti i canali</strong> che hai creato.",
			deleteAccountType: "Digita",
			deleteAccountPhrase: "Elimina questo account e tutti i miei canali per sempre",
			deleteAccountToConfirm: "per confermare",
			delete: "Elimina",
			terms: "Termini & Legale"
		},
		header: {
			profileSettings: "Profilo & Impostazioni",
			signIn: "Accedi con Google",
			acceptCookies: "Accetta cookie per accedere",
			legal: "Informazioni Legali",
			playlist: "Playlist",
			library: "Libreria",
			share: "Condividi",
			suggest: "Suggerisci",
			suggestionsDisabled: "Suggerimenti disabilitati (Solo Vista)",
			suggestSong: "Suggerisci Canzone",
			settings: "Impostazioni Canale",
			reviewRequests: "Esamina Richieste",
			allowSuggestions: "Consenti Suggerimenti",
			manualReview: "Revisione Manuale",
			approveKnown: "Approva noti",
			approveKnownTooltip: "Approva auto canzoni già approvate",
			musicOnly: "Solo Musica",
			maxLength: "Lunghezza Max",
			noLimit: "Nessun Limite",
			mins: "Min",
			maxQueueSize: "Coda Max",
			songs: "Canzoni",
			preventRepetition: "Evita Ripetizione",
			smartQueue: "Coda Smart",
			smartQueueTooltip: "Sostituisci canzoni con bassi voti se piena",
			autoRefill: "Riempimento Auto",
			autoRefillTooltip: "Aggiungi auto da cronologia se vuota. Inizia a 5 canzoni.",
			venueMode: "Modalità Locale",
			venueModeTooltip: "Ospiti vedono solo playlist (No Video)",
			allowPrelisten: "Pre-ascolto",
			allowVoting: "Voto",
			ownerBypassRules: "Propr. ignora regole",
			ownerBypassRulesTooltip: "Ignora filtri/limiti",
			ownerBypassQueue: "Propr. ignora coda",
			ownerBypassQueueTooltip: "Canzoni propr. suonano dopo (Priorità Top)",
			popups: "Popup",
			deleteChannel: "Elimina Canale",
			deleteChannelWarning: "Azione permanente.",
			deleteChannelTitle: "Elimina Canale?",
			deleteChannelConfirmPhrase: "Elimina questo canale per sempre",
			deleteChannelType: "Digita frase conferma...",
			leaveChannel: "Lasciare Canale?",
			leaveChannelConfirm: "Vuoi tornare alla lobby?",
			leave: "Lascia",
			copyUrl: "Copia URL",
			close: "Chiudi"
		},
		suggest: {
			placeholder: "Scrivi un titolo...",
			disabledPlaceholder: "Suggerimenti disabilitati",
			submit: "Invia",
			adding: "Aggiunta...",
			added: "Aggiunto",
			error: "Inserisci link YouTube o titolo."
		},
		app: {
			switching: "Cambio Canale...",
			channelNotFound: "Canale inesistente",
			notFoundMessage: "Il canale cercato ({roomId}) non è stato trovato.",
			goToLobby: "Vai alla Lobby",
			privateChannel: "Canale Privato",
			lockedMessage: "Canale protetto da password.",
			unlock: "Sblocca"
		},
		track: {
			playing: "In riproduzione",
			now: "Adesso",
			add: "Aggiungi",
			preview: "Anteprima",
			cancel: "Annulla",
			confirmDelete: "Conferma",
			delete: "Elimina",
			watch: "Su YouTube"
		}
	},
	pt: { // Portuguese
		lobby: {
			browseChannels: "Navegar Canais",
			public: "Público",
			private: "Privado",
			myChannels: "Meus Canais",
			searchPlaceholder: "Buscar canais...",
			connecting: "Conectando ao servidor...",
			createChannel: "Criar Canal",
			acceptCookies: "Aceitar Cookies",
			loginToCreate: "Login para Criar",
			noChannelsFound: "Nenhum canal encontrado para",
			live: "Ao vivo",
			createNewChannel: "Criar Novo Canal",
			channelName: "Nome do Canal",
			channelNamePlaceholder: "ex. Vibe da Noite",
			privacy: "Privacidade",
			passwordOptional: "Senha (Opcional)",
			passwordPlaceholder: "Deixe vazio para canal não listado",
			cancel: "Cancelar",
			enterPassword: "Digitar Senha",
			passwordInputPlaceholder: "Senha do canal...",
			unlockJoin: "Desbloquear & Entrar",
			welcome: "Bem-vindo",
			signOut: "Sair",
			signInGoogle: "Entrar com Google",
			deleteAccount: "Excluir Conta",
			deleteAccountConfirm: "Tem certeza?",
			deleteAccountWarning: "Esta ação não pode ser desfeita. Excluirá permanentemente sua conta e <strong>todos os canais</strong> criados.",
			deleteAccountType: "Digite",
			deleteAccountPhrase: "Excluir esta conta e todos os meus canais para sempre",
			deleteAccountToConfirm: "para confirmar",
			delete: "Excluir",
			terms: "Termos & Legal"
		},
		header: {
			profileSettings: "Perfil & Configurações",
			signIn: "Entrar com Google",
			acceptCookies: "Aceitar cookies para entrar",
			legal: "Informações Legais",
			playlist: "Playlist",
			library: "Biblioteca",
			share: "Compartilhar",
			suggest: "Sugerir",
			suggestionsDisabled: "Sugestões desativadas (Apenas Ver)",
			suggestSong: "Sugerir Música",
			settings: "Config. do Canal",
			reviewRequests: "Revisar Pedidos",
			allowSuggestions: "Permitir Sugestões",
			manualReview: "Revisão Manual",
			approveKnown: "Aprobar conhecidas",
			approveKnownTooltip: "Aprobar auto músicas já aprovadas antes",
			musicOnly: "Apenas Música",
			maxLength: "Duração Máx",
			noLimit: "Sem Limite",
			mins: "Min",
			maxQueueSize: "Tam. Máx Fila",
			songs: "Músicas",
			preventRepetition: "Evitar Repetição",
			smartQueue: "Fila Inteligente",
			smartQueueTooltip: "Substituir músicas baixo voto se cheia",
			autoRefill: "Reabastecer Auto",
			autoRefillTooltip: "Adicionar auto do histórico se vazia. Inicia com 5 músicas.",
			venueMode: "Modo Local",
			venueModeTooltip: "Convidados veem só playlist (Sem Vídeo)",
			allowPrelisten: "Pré-escuta",
			allowVoting: "Votação",
			ownerBypassRules: "Dono ignora regras",
			ownerBypassRulesTooltip: "Ignorar filtros/limites",
			ownerBypassQueue: "Dono ignora fila",
			ownerBypassQueueTooltip: "Músicas do dono tocam a seguir (Prioridade Top)",
			popups: "Popups",
			deleteChannel: "Excluir Canal",
			deleteChannelWarning: "Ação permanente.",
			deleteChannelTitle: "Excluir Canal?",
			deleteChannelConfirmPhrase: "Excluir este canal para sempre",
			deleteChannelType: "Digite frase de confirmação...",
			leaveChannel: "Sair do Canal?",
			leaveChannelConfirm: "Deseja voltar ao lobby?",
			leave: "Sair",
			copyUrl: "Copiar URL",
			close: "Fechar"
		},
		suggest: {
			placeholder: "Digite um título...",
			disabledPlaceholder: "Sugestões desativadas",
			submit: "Enviar",
			adding: "Adicionando...",
			added: "Adicionado",
			error: "Insira link YouTube ou título."
		},
		app: {
			switching: "Trocando Canal...",
			channelNotFound: "Canal não existe",
			notFoundMessage: "O canal procurado ({roomId}) não foi encontrado.",
			goToLobby: "Ir ao Lobby",
			privateChannel: "Canal Privado",
			lockedMessage: "Canal protegido por senha.",
			unlock: "Desbloquear"
		},
		track: {
			playing: "Tocando",
			now: "Agora",
			add: "Adicionar",
			preview: "Prévia",
			cancel: "Cancelar",
			confirmDelete: "Confirmar",
			delete: "Excluir",
			watch: "No YouTube"
		}
	}
};

export function LanguageProvider({ children }) {
	const [language, setLanguage] = useState(() => {
		return localStorage.getItem('cuevote_language') || 'en';
	});

	useEffect(() => {
		localStorage.setItem('cuevote_language', language);
	}, [language]);

	const t = (key, params = {}) => {
		const keys = key.split('.');
		let value = translations[language];

		for (const k of keys) {
			if (value && value[k]) {
				value = value[k];
			} else {
				// Fallback to English if key missing in current language
				let fallback = translations['en'];
				for (const fk of keys) {
					if (fallback && fallback[fk]) {
						fallback = fallback[fk];
					} else {
						return key; // Return key if not found anywhere
					}
				}
				value = fallback;
				break;
			}
		}

		if (typeof value === 'string') {
			return value.replace(/\{(\w+)\}/g, (match, param) => {
				return params[param] !== undefined ? params[param] : match;
			});
		}

		return value;
	};

	const value = {
		language,
		setLanguage,
		t
	};

	return (
		<LanguageContext.Provider value={value}>
			{children}
		</LanguageContext.Provider>
	);
}

export function useLanguage() {
	const context = useContext(LanguageContext);
	if (context === undefined) {
		throw new Error('useLanguage must be used within a LanguageProvider');
	}
	return context;
}
